[package]
name = "handler"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
futures = "0.3"
bytes = "1.1"
csv = "1.3.0"
arrow = "52.0.0"
datafusion = "40.0.0"